services:
  # Backend API
  - type: web
    name: docnest-backend
    runtime: docker
    region: oregon
    plan: starter
    branch: master
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    preDeployCommand: bash ./scripts/prestart.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docnest-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FIRST_SUPERUSER
        value: admin@example.com
      - key: FIRST_SUPERUSER_PASSWORD
        generateValue: true
      - key: PROJECT_NAME
        value: DocNest
      - key: BACKEND_CORS_ORIGINS
        value: https://docnest-frontend.onrender.com
      - key: ENVIRONMENT
        value: production

databases:
  - name: docnest-db
    databaseName: docnest_db
    user: docnest_db_user
    plan: free
    region: oregon
